### ISSUE TITLE
lib/ascii-char-map.js not found in version 1.0.0

### ISSUE THREAD

**Issue by rob-sto** [danmasta/ghost-gcs-adapter#17]
Thank you for the great work on the adapter!
I installed version 1.0.0 into a docker container (ghost 5.37.0) using the steps from the readme.
The adapter could not be loaded. After some investigation using the AdapterManager, I got an error message:
```
Error: Cannot find module './lib/ascii-char-map'
``` 
This file is part of the repo, but was not added when installing the npm package. After adding the missing file, the adapter seems to work fine.
Did I overlook something during the installation?

**Comment by danmasta** [comment]
Hi @rob-sto Thanks for the report! It looks like there was a missing file definition for `lib/**/*` in the package.json. I just updated it here https://github.com/danmasta/ghost-gcs-adapter/commit/d0cde6f7b914f4bca9c71b5f464ce788b77ef6b0 published v1.0.1 if you want to try again it should work now

**Comment by rob-sto** [comment]
Hi @danmasta,
`v1.0.1` works fine.
Thanks for the quick response!
