### ISSUE TITLE
Installation no longer works

### ISSUE THREAD

**Issue by rob-sto** [danmasta/ghost-gcs-adapter#18]
Hi!
I tried to install the adapter following the steps in https://github.com/danmasta/ghost-gcs-adapter?tab=readme-ov-file#installation but it no longer works. 

Getting a `404 not found error` for: https://registry.npmjs.org/@danmasta%2fghost-gcs-adapter

Is there an alternative way to install?
Thanks!

**Comment by danmasta** [comment]
Hi @rob-sto, sorry about that, I just updated the readme. You can still install from github like so:
```dockerfile
RUN mkdir -p /tmp/gcs && \
    curl -fsSL "https://api.github.com/repos/danmasta/ghost-gcs-adapter/tarball/master" | tar xz --strip-components=1 -C /tmp/gcs && \
    npm install --prefix /tmp/gcs --omit=dev --omit=optional --no-progress --loglevel error && \
    mv /tmp/gcs "${GHOST_INSTALL}/current/core/server/adapters/storage"

```

**Comment by rob-sto** [comment]
Thanks a lot for the quick response! Your solution works without problems.

I did not have `curl` installed and tried to download the release version from github the following way but could not get it working:
```
RUN mkdir -p /tmp/gcs
ADD https://github.com/danmasta/ghost-gcs-adapter/archive/refs/tags/v1.0.1.tar.gz /tmp
RUN tar -xzvf /tmp/v1.0.1.tar.gz --strip-components=1 -C /tmp/gcs && \
   npm install --prefix /tmp/gcs --omit=dev --omit=optional --no-progress --loglevel error && \
   mv /tmp/gcs "${GHOST_INSTALL}/current/core/server/adapters/storage"
```
There seems to be a difference between the master branch and release version 1.0.1

Thanks!

**Comment by danmasta** [comment]
@rob-sto Ah I see, that would probably still work, you just need to bump the version to `v1.0.2`, there was a change in one of the dependencies:
```dockerfile
ADD "https://github.com/danmasta/ghost-gcs-adapter/archive/refs/tags/v1.0.2.tar.gz" /tmp
```

You could also use a multi-stage build and copy the files to your final image like this:
```dockerfile
FROM node:22-bookworm-slim AS deps

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl

WORKDIR /tmp/gcs

RUN curl -fsSL "https://api.github.com/repos/danmasta/ghost-gcs-adapter/tarball/v1.0.2" | tar xz --strip-components=1 -C /tmp/gcs && \
    npm install --prefix /tmp/gcs --omit=dev --omit=optional --no-progress --loglevel error

FROM ghost:5.99.0

COPY --from=deps --chown=node:node /tmp/gcs "${GHOST_INSTALL}/current/core/server/adapters/storage/gcs"
```
