### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by WitchFreya** [danmasta/ghost-gcs-adapter#7]
Great work on the adapter! It's the only thing we've run into for GCS with Ghost at the moment that properly works with folders. The only issue we're having at the moment is that it doesn't currently support spaces in file names, is that something that would be possible to add?

**Comment by danmasta** [comment]
Hi @WitchFreya I know this is an old issue, and maybe you aren't even using this package anymore, but I just wanted to let you know that based on your feedback I updated the plugin to sanitize file name input based on the gcs file name [requirements](https://cloud.google.com/storage/docs/objects#naming). I also added support for ascii folding, based on the lucene database [implementation](https://github.com/apache/lucene/blob/main/lucene/analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.java#L190), which is a more robust way to sanitize input to the basic ascii characters and should improve stability for file name support dramatically.

Thank you for the feedback, and yes it did help. I appreciate it!
